### ISSUE TITLE
Hostname not used

### ISSUE THREAD

**Issue by kdre** [lfarkas/addon-netbird#3]
# Problem/Motivation

Just installed this addon and configured "homeassistant" as hostname.

## Expected behavior

The netbird dashboard should show "homeassistant.netbird.cloud" as a peer.

## Actual behavior

It shows "a3656363-netbird.netbird.cloud" as peer.
Also the addon page in homeassistantshows this hostname, not the one I configured.

**Comment by lfarkas** [comment]
are you sure to use my latest version?
could you copy here the logs here (last tab at the netbird addon page)

**Comment by kdre** [comment]
Additional information:
When I visit "app.netbird.io" and click on "..." next to my homeassistant peer and select "view" I see that the hostname "homeassistant" is correctly transferred. Anyway, the actual hostname ist not "homeassistant":

![image](https://github.com/lfarkas/addon-netbird/assets/1189361/5e79fa9d-345b-4bb7-b216-2892515c9c2c)

**Comment by lfarkas** [comment]
would you:
- remove the extension
- delete the pear from netbird admin ui
- install addon
- set setup key and hostname (this can be a fqdn eg: homeassistant.example.com)
- and only after this start the addon for the first time

**Comment by kdre** [comment]
Hi,
did what you proposed an it workes now! :-)

Anyway, the addon shows the wrong hostname on the start page:
![image](https://github.com/lfarkas/addon-netbird/assets/1189361/fa4d242a-b308-4f69-ab06-b750b08cc15b)

But this seems only to be a cosmetic problem...

Thanks!

**Comment by lfarkas** [comment]
yes i know but i can't fix it see other nne core addos
